apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name }}
spec:
  type: NodePort
  ports:
    - port: 1935
      targetPort: 1935
      protocol: TCP
      name: rtmp
  selector:
    app: {{ .Values.name | quote }}