apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: {{ .Values.namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: minikube.myhome
      http:
        paths:
          - path: /nginx-rtmp
            pathType: Prefix
            backend:
              service:
                name: nginx-rtmp-service
                port:
                  number: 1935