apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: {{ .Values.namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-server-service.hello
      http:
        paths:
          - path: /hello-server
            pathType: Prefix
            backend:
              service:
                name: hello-server-service
                port:
                  number: 8080